ealias zif='zypper info --provides --requires --recommends --suggests'
ealias zin='sudo zypper install --details'
ealias zre='sudo zypper refresh'
ealias zrm='sudo zypper remove --details'
ealias zse='zypper search'
ealias zdup='sudo zypper dup --details'
